function createData(food, traduction) {
	return { food, traduction };
}

export const fruits = [
	createData('Apple', 'Manzana'),
	createData('Banana', 'Banana'),
	createData('Cherry', 'Cereza'),
	createData('Date', 'Datil'),
	createData('Elderberry', 'Sauco'),
	createData('Fig', 'Higo'),
	createData('Grapes', 'Uvas'),
	createData('Honeydew melon', 'Melón honeydew'),
	createData('Lemon', 'Limón'),
	createData('Mango', 'Mango'),
	createData('Nectarine', 'Nectarina'),
	createData('Orange', 'Naranja'),
	createData('Peach', 'Melocotón'),
	createData('Pear', 'Pera'),
	createData('Quince', 'Membrillo'),
	createData('Raspberry', 'Frambuesa'),
	createData('Strawberry', 'Fresa'),
	createData('Tangerine', 'Mandarina'),
	createData('Ugli fruit', 'Fruta Ugli'),
	createData('Watermelon', 'Sandía'),
];

export const vegetables = [
	createData('Artichoke', 'Alcachofa'),
	createData('Beet', 'Remolacha'),
	createData('Carrot', 'Zanahoria'),
	createData('Daikon', 'Daikon'),
	createData('Eggplant', 'Berenjena'),
	createData('Fennel', 'Hinojo'),
	createData('Green bean', 'Ejote verde'),
	createData('Horseradish', 'Rábano picante'),
	createData('Iceberg lettuce', 'Lechuga iceberg'),
	createData('Jicama', 'Jicama'),
	createData('Kale', 'Col rizada'),
	createData('Leek', 'Puerro'),
	createData('Mushroom', 'Champiñón'),
	createData('Onion', 'Cebolla'),
	createData('Parsnip', 'Chirivía'),
	createData('Quinoa', 'Quinoa'),
	createData('Radish', 'Rábano'),
	createData('Spinach', 'Espinaca'),
	createData('Turnip', 'Nabo'),
	createData('Zucchini', 'Calabacín'),
];

export const meats = [
	createData('Angelfish', 'Pez ángel'),
	createData('Barracuda', 'Barracuda'),
	createData('Clownfish', 'Pez payaso'),
	createData('Cod', 'Bacalao'),
	createData('Eel', 'Anguila'),
	createData('Flounder', 'Platija'),
	createData('Grouper', 'Mero'),
	createData('Herring', 'Arenque'),
	createData('Jellyfish', 'Medusa'),
	createData('Koi', 'Koi'),
	createData('Lionfish', 'Pez león'),
	createData('Manta ray', 'Manta'),
	createData('Nurse shark', 'Tiburón enfermera'),
	createData('Octopus', 'Pulpo'),
	createData('Perch', 'Perca'),
	createData('Quinnat salmon', 'Salmón quinnat'),
	createData('Rainbow trout', 'Trucha arcoíris'),
	createData('Sardine', 'Sardina'),
	createData('Tuna', 'Atún'),
	createData('Unicorn fish', 'Pez unicornio'),
];
