function createData(animal, traduction) {
	return { animal, traduction };
}

export const mammals = [
	createData('Badger', 'Tejón'),
	createData('Bat', 'Murciélago'),
	createData('Bear', 'Oso'),
	createData('Beaver', 'Castor'),
	createData('Beluga', 'Beluga'),
	createData('Bobcat', 'Bobcat'),
	createData('Cat', 'Gato'),
	createData('Chipmunk', 'Ardilla terrestre'),
	createData('Cheetah', 'Guepardo'),
	createData('Coyote', 'Coyote'),
	createData('Deer', 'Ciervo'),
	createData('Dormouse', 'Topillo'),
	createData('Dog', 'Perro'),
	createData('Elephant', 'Elefante'),
	createData('Elk', 'Alce'),
	createData('Ferret', 'Hurón'),
	createData('Fox', 'Zorro'),
	createData('Giraffe', 'Jirafa'),
	createData('Gorilla', 'Gorila'),
	createData('Hippopotamus', 'Hipopótamo'),
	createData('Jaguar', 'Jaguar'),
	createData('Lemming', 'Lemming'),
	createData('Lion', 'León'),
	createData('Lynx', 'Lince'),
	createData('Marten', 'Marta'),
	createData('Mink', 'Vison'),
	createData('Mole', 'Talpa'),
	createData('Moose', 'Alce americano'),
	createData('Muskrat', 'Ratón almizclero'),
	createData('Muskox', 'Muskox'),
	createData('Narwhal', 'Narval'),
	createData('Ocelot', 'Ocelote'),
	createData('Opossum', 'Possum'),
	createData('Otter', 'Nutria'),
	createData('Puma', 'Puma'),
	createData('Plaice', 'Plaice'),
	createData('Porcupine', 'Puercoespín'),
	createData('Rabbit', 'Conejo'),
	createData('Raccoon ', 'Mapache'),
	createData('Rat ', 'Rata'),
	createData('Shrew ', 'Musaraña'),
	createData('Skunk ', 'Mofeta'),
	createData('Squirrel ', 'Ardilla'),
	createData('Tiger ', 'Tigre'),
	createData('Vole ', 'Vole'),
	createData('Weasel ', 'Comadreja'),
	createData('Wolf ', 'Lobo'),
	createData('Mouse ', 'Ratón'),
	createData('Monkey ', 'Mono'),
];

export const reptiles = [
	createData('Alligator', 'Cocodrilo'),
	createData('Anaconda', 'Anaconda'),
	createData('Chameleon', 'Camaleón'),
	createData('Cobra', 'Cobra'),
	createData('Crocodile', 'Cocodrilo'),
	createData('Garter snake', 'Serpiente de la cinta'),
	createData('Gecko', 'Gecko'),
	createData('Iguana', 'Iguana'),
	createData('Komodo dragon', 'Dragón de Komodo'),
	createData('Lizard', 'Lagarto'),
	createData('Monitor lizard', 'Lagarto monitor'),
	createData('Python', 'Pitón'),
	createData('Rattlesnake', 'Cascabel'),
	createData('Sea turtle', 'Tortuga marina'),
	createData('Skink', 'Escinco'),
	createData('Snake', 'Serpiente'),
	createData('Spinytail iguana', 'Iguana cola espina'),
	createData('Tortoise', 'Tortuga'),
	createData('Tuatara', 'Tuatara'),
	createData('Viper', 'Víbora'),
];

export const fishes = [
	createData('Angelfish', 'Pez ángel'),
	createData('Barracuda', 'Barracuda'),
	createData('Clownfish', 'Pez payaso'),
	createData('Cod', 'Bacalao'),
	createData('Eel', 'Anguila'),
	createData('Flounder', 'Platija'),
	createData('Grouper', 'Mero'),
	createData('Herring', 'Arenque'),
	createData('Jellyfish', 'Medusa'),
	createData('Koi', 'Koi'),
	createData('Lionfish', 'Pez león'),
	createData('Manta ray', 'Manta'),
	createData('Nurse shark', 'Tiburón enfermera'),
	createData('Octopus', 'Pulpo'),
	createData('Perch', 'Perca'),
	createData('Quinnat salmon', 'Salmón quinnat'),
	createData('Rainbow trout', 'Trucha arcoíris'),
	createData('Sardine', 'Sardina'),
	createData('Tuna', 'Atún'),
	createData('Unicorn fish', 'Pez unicornio'),
];
