function createData(clothes, traduction) {
	return { clothes, traduction };
}

export const firstcloths = [
	createData('Blazer', 'Blazer'),
	createData('Boots', 'Botas'),
	createData('Bowtie', 'Pajarita'),
	createData('Cap', 'Gorra'),
	createData('Cardigan', 'Cardigan'),
	createData('Clogs', 'Zuecos'),
	createData('Coat', 'Abrigo'),
	createData('Crop top', 'Top corto'),
	createData('Crop pants', 'Pantalones cortos'),
	createData('Cufflinks', 'Gemelos'),
	createData('Cummerbund', 'Faja'),
	createData('Dress', 'Vestido'),
	createData('Espadrilles', 'Espadrilles'),
	createData('Evening gown', 'Vestido de noche'),
	createData('Flannel', 'Franela'),
	createData('Flip-flops', 'Chanclas'),
	createData('Gauchos', 'Gauchos'),
	createData('Gilet', 'Chaleco'),
	createData('Gloves', 'Guantes'),
	createData('Hat', 'Sombrero'),
	createData('Hoodie', 'Sudadera con capucha'),
];

export const secondList = [
	createData('Jeans', 'Jeans'),
	createData('Jewelry', 'Joyas'),
	createData('Jacket', 'Chaqueta'),
	createData('Kaftan', 'Kaftán'),
	createData('Kimono', 'Kimono'),
	createData('Leggings', 'Leggings'),
	createData('Moccasins', 'Mocasines'),
	createData('Mules', 'Mulas'),
	createData('Pants', 'Pantalones'),
	createData('Poncho', 'Poncho'),
	createData('Raincoat', 'Impermeable'),
	createData('Romper', 'Mono'),
	createData('Rompers', 'Monos'),
	createData('Scarf', 'Bufanda'),
	createData('Sandals', 'Sandalias'),
	createData('Shirt', 'Camisa'),
	createData('Shoes', 'Zapatos'),
	createData('Shorts', 'Pantalones cortos'),
	createData('Socks', 'Calcetines'),
	createData('Sneakers', 'Zapatillas de deporte'),
	createData('Sarong', 'Sarong'),
	createData('Shawl', 'Manta'),
	createData('Slacks', 'Pantalones'),
	createData('Suit', 'Traje'),
	createData('Sun hat', 'Sombrero de sol'),
	createData('Sweater', 'Suéter'),
	createData('Suspenders', 'Tirantes'),
	createData('Swimsuit', 'Bañador'),
];

export const thirthList = [
	createData('T-Shirt', 'Camiseta'),
	createData('Ties', 'Corbatas'),
	createData('Tights', 'Medias'),
	createData('Tracksuit', 'Chándal'),
	createData('Tunic', 'Túnica'),
	createData('Underwear', 'Ropa interior'),
	createData('Vest', 'Chaleco'),
	createData('Wallet', 'Cartera'),
	createData('Windbreaker', 'Cazadora viento'),
	createData('Wrap dress', 'Vestido envuelto'),
];
