function createData(part, traduction) {
	return { part, traduction };
}

export const bones = [
	createData('Skull', 'Cráneo'),
	createData('Spine', 'Columna vertebral'),
	createData('Ribs', 'Costillas'),
	createData('Humerus', 'Húmero'),
	createData('Ulna', 'Cúbito'),
	createData('Radius', 'Radio'),
	createData('Carpals', 'Carpianos'),
	createData('Metacarpals', 'Metacarpianos'),
	createData('Phalanges', 'Falanges'),
	createData('Femur', 'Fémur'),
	createData('Patella', 'Rótula'),
	createData('Tibia', 'Tibia'),
	createData('Fibula', 'Peroné'),
	createData('Tarsals', 'Tarso'),
	createData('Metatarsals', 'Metatarso'),
	createData('Pelvis', 'Pelvis'),
	createData('Scapula', 'Escápula'),
	createData('Clavicle', 'Clavícula'),
	createData('Sternum', 'Esterón'),
	createData('Collarbone', 'Clavícula'),
];

export const muscles = [
	createData('Biceps', 'Bíceps'),
	createData('Triceps', 'Tríceps'),
	createData('Deltoid', 'Deltoides'),
	createData('Pectoral', 'Pectoral'),
	createData('Abdominal', 'Abdominal'),
	createData('Quadriceps', 'Cuádriceps'),
	createData('Hamstrings', 'Isquiotibiales'),
	createData('Gastrocnemius', 'Gastrocnemio'),
	createData('Soleus', 'Soleo'),
	createData('Trapezius', 'Trapecio'),
	createData('Latissimus dorsi', 'Dorsal ancho'),
	createData('Rhomboids', 'Romboides'),
	createData('Erector spinae', 'Erector espinal'),
	createData('Serratus anterior', 'Serrato anterior'),
	createData('Rectus abdominis', 'Abdominal recto'),
	createData('Obliques', 'Oblícuos'),
	createData('Gluteus maximus', 'Glúteo máximo'),
	createData('Adductors', 'Aductores'),
	createData('Sartorius', 'Sartorio'),
];

export const organs = [
	createData('Heart', 'Corazón'),
	createData('Lungs', 'Pulmones'),
	createData('Liver', 'Hígado'),
	createData('Stomach', 'Estómago'),
	createData('Intestines', 'Intestinos'),
	createData('Kidneys', 'Riñones'),
	createData('Bladder', 'Vejiga'),
	createData('Spleen', 'Bazo'),
	createData('Pancreas', 'Páncreas'),
	createData('Thyroid', 'Tiroides'),
	createData('Adrenal gland', 'Glándula suprarrenal'),
	createData('Ovaries', 'Ovarios'),
	createData('Testes', 'Testículos'),
	createData('Prostate', 'Próstata'),
	createData('Uterus', 'Útero'),
	createData('Eyes', 'Ojos'),
	createData('Ears', 'Oídos'),
	createData('Nose', 'Nariz'),
	createData('Mouth', 'Boca'),
];
